security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email  # l'email sera utilisé comme identifiant de connexion

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: login       # route pour le formulaire de connexion
                check_path: login       # route où Symfony vérifie les identifiants
            logout:
                path: logout
                target: /               # redirection après déconnexion

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }  # back-office accessible seulement aux admins
