# config/services.yaml

# -------------------------------
# Paramètres globaux
# -------------------------------
parameters:
    images_directory: '%kernel.project_dir%/public/images'

# -------------------------------
# Services auto-wire
# -------------------------------
services:
    # Auto-wire tous les services de src/
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
        autowire: true
        autoconfigure: true

    # Stripe client
    stripe.client:
        class: 'Stripe\StripeClient'
        arguments:
            - '%env(STRIPE_SECRET_KEY)%'

    # Service Stripe personnalisé
    App\Service\StripeService:
        arguments:
            $stripeClient: '@stripe.client'